<?xml version="1.0" encoding="utf-8"?><Database Name="linq" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CADAVILES03\SQLEXPRESS;Initial Catalog=linq;Integrated Security=True" SettingsObjectName="ejercicio1.Properties.Settings" SettingsPropertyName="linqConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.clientes" Member="clientes">
    <Type Name="clientes">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.buscarcliente" Method="buscarcliente">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="buscarclienteResult">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.EliminarCliente" Method="EliminarCliente">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarCliente" Method="insertarCliente">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido1" Parameter="apellido1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido2" Parameter="apellido2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.listartodos" Method="listartodos">
    <ElementType Name="listartodosResult">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Modificarcliente" Method="Modificarcliente">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido1" Parameter="apellido1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido2" Parameter="apellido2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>