#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ejercicio_hospital")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDept(Dept instance);
    partial void UpdateDept(Dept instance);
    partial void DeleteDept(Dept instance);
    partial void InsertEmp(Emp instance);
    partial void UpdateEmp(Emp instance);
    partial void DeleteEmp(Emp instance);
    partial void InsertHospital(Hospital instance);
    partial void UpdateHospital(Hospital instance);
    partial void DeleteHospital(Hospital instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::hospital.Properties.Settings.Default.ejercicio_hospitalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Dept> Dept
		{
			get
			{
				return this.GetTable<Dept>();
			}
		}
		
		public System.Data.Linq.Table<Doctor> Doctor
		{
			get
			{
				return this.GetTable<Doctor>();
			}
		}
		
		public System.Data.Linq.Table<Emp> Emp
		{
			get
			{
				return this.GetTable<Emp>();
			}
		}
		
		public System.Data.Linq.Table<Enfermo> Enfermo
		{
			get
			{
				return this.GetTable<Enfermo>();
			}
		}
		
		public System.Data.Linq.Table<Hospital> Hospital
		{
			get
			{
				return this.GetTable<Hospital>();
			}
		}
		
		public System.Data.Linq.Table<Plantilla> Plantilla
		{
			get
			{
				return this.GetTable<Plantilla>();
			}
		}
		
		public System.Data.Linq.Table<Sala> Sala
		{
			get
			{
				return this.GetTable<Sala>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscarenfermo")]
		public ISingleResult<buscarenfermoResult> buscarenfermo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inscripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inscripcion);
			return ((ISingleResult<buscarenfermoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarenfermo")]
		public int eliminarenfermo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inscripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inscripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarenfermo")]
		public int insertarenfermo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inscripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numero)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, inscripcion, sexo, fecha, direccion, numero);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listartodos")]
		public ISingleResult<listartodosResult> listartodos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listartodosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarenfermo")]
		public int modificarenfermo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> inscripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(2)")] string sexo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numero)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, inscripcion, sexo, fecha, direccion, numero);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.obtenerempleados")]
		public ISingleResult<obtenerempleadosResult> obtenerempleados([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> fechainicial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> fechafinal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> valordepartamento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fechainicial, fechafinal, valordepartamento);
			return ((ISingleResult<obtenerempleadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscardoctor")]
		public ISingleResult<buscardoctorResult> buscardoctor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numerodoctor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numerodoctor);
			return ((ISingleResult<buscardoctorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.buscarsala")]
		public ISingleResult<buscarsalaResult> buscarsala([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigosala)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigosala);
			return ((ISingleResult<buscarsalaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminardoctor")]
		public int eliminardoctor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numerodoctor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numerodoctor);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarsala")]
		public int eliminarsala([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigosala)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigosala);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertardoctor")]
		public int insertardoctor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigohospital, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numerodoctor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombredoctor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string especialidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigohospital, numerodoctor, nombredoctor, especialidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarsala")]
		public int insertarsala([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigosala, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigohospital, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombresala, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string especialidadsala)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigosala, codigohospital, nombresala, especialidadsala);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listardoctores")]
		public ISingleResult<listardoctoresResult> listardoctores()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listardoctoresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarsalas")]
		public ISingleResult<listarsalasResult> listarsalas()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarsalasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificardoctor")]
		public int modificardoctor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigohospital, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numerodoctor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombredoctor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string especialidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigohospital, numerodoctor, nombredoctor, especialidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarsala2")]
		public int modificarsala2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigosala, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigohospital, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombresala, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string especialidadsala)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigosala, codigohospital, nombresala, especialidadsala);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dept")]
	public partial class Dept : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Dept_No;
		
		private string _DNombre;
		
		private string _Loc;
		
		private System.Nullable<int> _Cod_Hospital;
		
		private EntitySet<Emp> _Emp;
		
		private EntityRef<Hospital> _Hospital;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDept_NoChanging(int value);
    partial void OnDept_NoChanged();
    partial void OnDNombreChanging(string value);
    partial void OnDNombreChanged();
    partial void OnLocChanging(string value);
    partial void OnLocChanged();
    partial void OnCod_HospitalChanging(System.Nullable<int> value);
    partial void OnCod_HospitalChanged();
    #endregion
		
		public Dept()
		{
			this._Emp = new EntitySet<Emp>(new Action<Emp>(this.attach_Emp), new Action<Emp>(this.detach_Emp));
			this._Hospital = default(EntityRef<Hospital>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Dept_No
		{
			get
			{
				return this._Dept_No;
			}
			set
			{
				if ((this._Dept_No != value))
				{
					this.OnDept_NoChanging(value);
					this.SendPropertyChanging();
					this._Dept_No = value;
					this.SendPropertyChanged("Dept_No");
					this.OnDept_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNombre", DbType="VarChar(50)")]
		public string DNombre
		{
			get
			{
				return this._DNombre;
			}
			set
			{
				if ((this._DNombre != value))
				{
					this.OnDNombreChanging(value);
					this.SendPropertyChanging();
					this._DNombre = value;
					this.SendPropertyChanged("DNombre");
					this.OnDNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loc", DbType="VarChar(50)")]
		public string Loc
		{
			get
			{
				return this._Loc;
			}
			set
			{
				if ((this._Loc != value))
				{
					this.OnLocChanging(value);
					this.SendPropertyChanging();
					this._Loc = value;
					this.SendPropertyChanged("Loc");
					this.OnLocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Hospital", DbType="Int")]
		public System.Nullable<int> Cod_Hospital
		{
			get
			{
				return this._Cod_Hospital;
			}
			set
			{
				if ((this._Cod_Hospital != value))
				{
					if (this._Hospital.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCod_HospitalChanging(value);
					this.SendPropertyChanging();
					this._Cod_Hospital = value;
					this.SendPropertyChanged("Cod_Hospital");
					this.OnCod_HospitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dept_Emp", Storage="_Emp", ThisKey="Dept_No", OtherKey="Dept_No")]
		public EntitySet<Emp> Emp
		{
			get
			{
				return this._Emp;
			}
			set
			{
				this._Emp.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hospital_Dept", Storage="_Hospital", ThisKey="Cod_Hospital", OtherKey="Hospital_cod", IsForeignKey=true)]
		public Hospital Hospital
		{
			get
			{
				return this._Hospital.Entity;
			}
			set
			{
				Hospital previousValue = this._Hospital.Entity;
				if (((previousValue != value) 
							|| (this._Hospital.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hospital.Entity = null;
						previousValue.Dept.Remove(this);
					}
					this._Hospital.Entity = value;
					if ((value != null))
					{
						value.Dept.Add(this);
						this._Cod_Hospital = value.Hospital_cod;
					}
					else
					{
						this._Cod_Hospital = default(Nullable<int>);
					}
					this.SendPropertyChanged("Hospital");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Emp(Emp entity)
		{
			this.SendPropertyChanging();
			entity.Dept = this;
		}
		
		private void detach_Emp(Emp entity)
		{
			this.SendPropertyChanging();
			entity.Dept = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doctor")]
	public partial class Doctor
	{
		
		private System.Nullable<int> _Hospital_Cod;
		
		private System.Nullable<int> _Doctor_No;
		
		private string _Apellido;
		
		private string _Especialidad;
		
		public Doctor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Cod", DbType="Int")]
		public System.Nullable<int> Hospital_Cod
		{
			get
			{
				return this._Hospital_Cod;
			}
			set
			{
				if ((this._Hospital_Cod != value))
				{
					this._Hospital_Cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doctor_No", DbType="Int")]
		public System.Nullable<int> Doctor_No
		{
			get
			{
				return this._Doctor_No;
			}
			set
			{
				if ((this._Doctor_No != value))
				{
					this._Doctor_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Emp")]
	public partial class Emp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Emp_No;
		
		private string _Apellido;
		
		private string _Oficio;
		
		private System.Nullable<int> _Dir;
		
		private System.Nullable<System.DateTime> _Fecha_Alt;
		
		private System.Nullable<decimal> _Salario;
		
		private System.Nullable<decimal> _Comision;
		
		private System.Nullable<int> _Dept_No;
		
		private EntityRef<Dept> _Dept;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmp_NoChanging(int value);
    partial void OnEmp_NoChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnOficioChanging(string value);
    partial void OnOficioChanged();
    partial void OnDirChanging(System.Nullable<int> value);
    partial void OnDirChanged();
    partial void OnFecha_AltChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_AltChanged();
    partial void OnSalarioChanging(System.Nullable<decimal> value);
    partial void OnSalarioChanged();
    partial void OnComisionChanging(System.Nullable<decimal> value);
    partial void OnComisionChanged();
    partial void OnDept_NoChanging(System.Nullable<int> value);
    partial void OnDept_NoChanged();
    #endregion
		
		public Emp()
		{
			this._Dept = default(EntityRef<Dept>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_No", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Emp_No
		{
			get
			{
				return this._Emp_No;
			}
			set
			{
				if ((this._Emp_No != value))
				{
					this.OnEmp_NoChanging(value);
					this.SendPropertyChanging();
					this._Emp_No = value;
					this.SendPropertyChanged("Emp_No");
					this.OnEmp_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oficio", DbType="VarChar(50)")]
		public string Oficio
		{
			get
			{
				return this._Oficio;
			}
			set
			{
				if ((this._Oficio != value))
				{
					this.OnOficioChanging(value);
					this.SendPropertyChanging();
					this._Oficio = value;
					this.SendPropertyChanged("Oficio");
					this.OnOficioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="Int")]
		public System.Nullable<int> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this.OnDirChanging(value);
					this.SendPropertyChanging();
					this._Dir = value;
					this.SendPropertyChanged("Dir");
					this.OnDirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Alt", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Alt
		{
			get
			{
				return this._Fecha_Alt;
			}
			set
			{
				if ((this._Fecha_Alt != value))
				{
					this.OnFecha_AltChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Alt = value;
					this.SendPropertyChanged("Fecha_Alt");
					this.OnFecha_AltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salario", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> Salario
		{
			get
			{
				return this._Salario;
			}
			set
			{
				if ((this._Salario != value))
				{
					this.OnSalarioChanging(value);
					this.SendPropertyChanging();
					this._Salario = value;
					this.SendPropertyChanged("Salario");
					this.OnSalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comision", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> Comision
		{
			get
			{
				return this._Comision;
			}
			set
			{
				if ((this._Comision != value))
				{
					this.OnComisionChanging(value);
					this.SendPropertyChanging();
					this._Comision = value;
					this.SendPropertyChanged("Comision");
					this.OnComisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept_No", DbType="Int")]
		public System.Nullable<int> Dept_No
		{
			get
			{
				return this._Dept_No;
			}
			set
			{
				if ((this._Dept_No != value))
				{
					if (this._Dept.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDept_NoChanging(value);
					this.SendPropertyChanging();
					this._Dept_No = value;
					this.SendPropertyChanged("Dept_No");
					this.OnDept_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Dept_Emp", Storage="_Dept", ThisKey="Dept_No", OtherKey="Dept_No", IsForeignKey=true)]
		public Dept Dept
		{
			get
			{
				return this._Dept.Entity;
			}
			set
			{
				Dept previousValue = this._Dept.Entity;
				if (((previousValue != value) 
							|| (this._Dept.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Dept.Entity = null;
						previousValue.Emp.Remove(this);
					}
					this._Dept.Entity = value;
					if ((value != null))
					{
						value.Emp.Add(this);
						this._Dept_No = value.Dept_No;
					}
					else
					{
						this._Dept_No = default(Nullable<int>);
					}
					this.SendPropertyChanged("Dept");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Enfermo")]
	public partial class Enfermo
	{
		
		private System.Nullable<int> _inscripcion;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private System.Nullable<int> _Dir;
		
		private System.Nullable<System.DateTime> _Fecha_Nac;
		
		private string _S;
		
		private System.Nullable<int> _NSS;
		
		private System.Nullable<int> _Cod_Hospital;
		
		public Enfermo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscripcion", DbType="Int")]
		public System.Nullable<int> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				if ((this._inscripcion != value))
				{
					this._inscripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="Int")]
		public System.Nullable<int> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this._Dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nac", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Nac
		{
			get
			{
				return this._Fecha_Nac;
			}
			set
			{
				if ((this._Fecha_Nac != value))
				{
					this._Fecha_Nac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S", DbType="VarChar(2)")]
		public string S
		{
			get
			{
				return this._S;
			}
			set
			{
				if ((this._S != value))
				{
					this._S = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSS", DbType="Int")]
		public System.Nullable<int> NSS
		{
			get
			{
				return this._NSS;
			}
			set
			{
				if ((this._NSS != value))
				{
					this._NSS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Hospital", DbType="Int")]
		public System.Nullable<int> Cod_Hospital
		{
			get
			{
				return this._Cod_Hospital;
			}
			set
			{
				if ((this._Cod_Hospital != value))
				{
					this._Cod_Hospital = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hospital")]
	public partial class Hospital : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Hospital_cod;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private System.Nullable<int> _num_cama;
		
		private EntitySet<Dept> _Dept;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHospital_codChanging(int value);
    partial void OnHospital_codChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void Onnum_camaChanging(System.Nullable<int> value);
    partial void Onnum_camaChanged();
    #endregion
		
		public Hospital()
		{
			this._Dept = new EntitySet<Dept>(new Action<Dept>(this.attach_Dept), new Action<Dept>(this.detach_Dept));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_cod", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Hospital_cod
		{
			get
			{
				return this._Hospital_cod;
			}
			set
			{
				if ((this._Hospital_cod != value))
				{
					this.OnHospital_codChanging(value);
					this.SendPropertyChanging();
					this._Hospital_cod = value;
					this.SendPropertyChanged("Hospital_cod");
					this.OnHospital_codChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_cama", DbType="Int")]
		public System.Nullable<int> num_cama
		{
			get
			{
				return this._num_cama;
			}
			set
			{
				if ((this._num_cama != value))
				{
					this.Onnum_camaChanging(value);
					this.SendPropertyChanging();
					this._num_cama = value;
					this.SendPropertyChanged("num_cama");
					this.Onnum_camaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hospital_Dept", Storage="_Dept", ThisKey="Hospital_cod", OtherKey="Cod_Hospital")]
		public EntitySet<Dept> Dept
		{
			get
			{
				return this._Dept;
			}
			set
			{
				this._Dept.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Dept(Dept entity)
		{
			this.SendPropertyChanging();
			entity.Hospital = this;
		}
		
		private void detach_Dept(Dept entity)
		{
			this.SendPropertyChanging();
			entity.Hospital = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Plantilla")]
	public partial class Plantilla
	{
		
		private System.Nullable<int> _Hospital_Cod;
		
		private System.Nullable<int> _Sala_Cod;
		
		private System.Nullable<int> _Empleado_No;
		
		private string _Apellido;
		
		private string _Funcion;
		
		private string _T;
		
		private System.Nullable<decimal> _Salario;
		
		public Plantilla()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Cod", DbType="Int")]
		public System.Nullable<int> Hospital_Cod
		{
			get
			{
				return this._Hospital_Cod;
			}
			set
			{
				if ((this._Hospital_Cod != value))
				{
					this._Hospital_Cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sala_Cod", DbType="Int")]
		public System.Nullable<int> Sala_Cod
		{
			get
			{
				return this._Sala_Cod;
			}
			set
			{
				if ((this._Sala_Cod != value))
				{
					this._Sala_Cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empleado_No", DbType="Int")]
		public System.Nullable<int> Empleado_No
		{
			get
			{
				return this._Empleado_No;
			}
			set
			{
				if ((this._Empleado_No != value))
				{
					this._Empleado_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Funcion", DbType="VarChar(50)")]
		public string Funcion
		{
			get
			{
				return this._Funcion;
			}
			set
			{
				if ((this._Funcion != value))
				{
					this._Funcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T", DbType="VarChar(15)")]
		public string T
		{
			get
			{
				return this._T;
			}
			set
			{
				if ((this._T != value))
				{
					this._T = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salario", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> Salario
		{
			get
			{
				return this._Salario;
			}
			set
			{
				if ((this._Salario != value))
				{
					this._Salario = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sala")]
	public partial class Sala
	{
		
		private System.Nullable<int> _Sala_Cod;
		
		private System.Nullable<int> _Cod_Hospital;
		
		private string _Nombre;
		
		private string _Especialidad;
		
		public Sala()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sala_Cod", DbType="Int")]
		public System.Nullable<int> Sala_Cod
		{
			get
			{
				return this._Sala_Cod;
			}
			set
			{
				if ((this._Sala_Cod != value))
				{
					this._Sala_Cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Hospital", DbType="Int")]
		public System.Nullable<int> Cod_Hospital
		{
			get
			{
				return this._Cod_Hospital;
			}
			set
			{
				if ((this._Cod_Hospital != value))
				{
					this._Cod_Hospital = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
	}
	
	public partial class buscarenfermoResult
	{
		
		private System.Nullable<int> _inscripcion;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private System.Nullable<int> _Dir;
		
		private System.Nullable<System.DateTime> _Fecha_Nac;
		
		private string _S;
		
		private System.Nullable<int> _NSS;
		
		private System.Nullable<int> _Cod_Hospital;
		
		public buscarenfermoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscripcion", DbType="Int")]
		public System.Nullable<int> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				if ((this._inscripcion != value))
				{
					this._inscripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="Int")]
		public System.Nullable<int> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this._Dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nac", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Nac
		{
			get
			{
				return this._Fecha_Nac;
			}
			set
			{
				if ((this._Fecha_Nac != value))
				{
					this._Fecha_Nac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S", DbType="VarChar(2)")]
		public string S
		{
			get
			{
				return this._S;
			}
			set
			{
				if ((this._S != value))
				{
					this._S = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSS", DbType="Int")]
		public System.Nullable<int> NSS
		{
			get
			{
				return this._NSS;
			}
			set
			{
				if ((this._NSS != value))
				{
					this._NSS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Hospital", DbType="Int")]
		public System.Nullable<int> Cod_Hospital
		{
			get
			{
				return this._Cod_Hospital;
			}
			set
			{
				if ((this._Cod_Hospital != value))
				{
					this._Cod_Hospital = value;
				}
			}
		}
	}
	
	public partial class listartodosResult
	{
		
		private System.Nullable<int> _inscripcion;
		
		private string _Apellido;
		
		private string _Direccion;
		
		private System.Nullable<int> _Dir;
		
		private System.Nullable<System.DateTime> _Fecha_Nac;
		
		private string _S;
		
		private System.Nullable<int> _NSS;
		
		private System.Nullable<int> _Cod_Hospital;
		
		public listartodosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscripcion", DbType="Int")]
		public System.Nullable<int> inscripcion
		{
			get
			{
				return this._inscripcion;
			}
			set
			{
				if ((this._inscripcion != value))
				{
					this._inscripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="Int")]
		public System.Nullable<int> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this._Dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nac", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Nac
		{
			get
			{
				return this._Fecha_Nac;
			}
			set
			{
				if ((this._Fecha_Nac != value))
				{
					this._Fecha_Nac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S", DbType="VarChar(2)")]
		public string S
		{
			get
			{
				return this._S;
			}
			set
			{
				if ((this._S != value))
				{
					this._S = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSS", DbType="Int")]
		public System.Nullable<int> NSS
		{
			get
			{
				return this._NSS;
			}
			set
			{
				if ((this._NSS != value))
				{
					this._NSS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Hospital", DbType="Int")]
		public System.Nullable<int> Cod_Hospital
		{
			get
			{
				return this._Cod_Hospital;
			}
			set
			{
				if ((this._Cod_Hospital != value))
				{
					this._Cod_Hospital = value;
				}
			}
		}
	}
	
	public partial class obtenerempleadosResult
	{
		
		private int _Emp_No;
		
		private string _Apellido;
		
		private string _Oficio;
		
		private System.Nullable<int> _Dir;
		
		private System.Nullable<System.DateTime> _Fecha_Alt;
		
		private System.Nullable<decimal> _Salario;
		
		private System.Nullable<decimal> _Comision;
		
		private System.Nullable<int> _Dept_No;
		
		public obtenerempleadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_No", DbType="Int NOT NULL")]
		public int Emp_No
		{
			get
			{
				return this._Emp_No;
			}
			set
			{
				if ((this._Emp_No != value))
				{
					this._Emp_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oficio", DbType="VarChar(50)")]
		public string Oficio
		{
			get
			{
				return this._Oficio;
			}
			set
			{
				if ((this._Oficio != value))
				{
					this._Oficio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dir", DbType="Int")]
		public System.Nullable<int> Dir
		{
			get
			{
				return this._Dir;
			}
			set
			{
				if ((this._Dir != value))
				{
					this._Dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Alt", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Fecha_Alt
		{
			get
			{
				return this._Fecha_Alt;
			}
			set
			{
				if ((this._Fecha_Alt != value))
				{
					this._Fecha_Alt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salario", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> Salario
		{
			get
			{
				return this._Salario;
			}
			set
			{
				if ((this._Salario != value))
				{
					this._Salario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comision", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> Comision
		{
			get
			{
				return this._Comision;
			}
			set
			{
				if ((this._Comision != value))
				{
					this._Comision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept_No", DbType="Int")]
		public System.Nullable<int> Dept_No
		{
			get
			{
				return this._Dept_No;
			}
			set
			{
				if ((this._Dept_No != value))
				{
					this._Dept_No = value;
				}
			}
		}
	}
	
	public partial class buscardoctorResult
	{
		
		private System.Nullable<int> _Hospital_Cod;
		
		private System.Nullable<int> _Doctor_No;
		
		private string _Apellido;
		
		private string _Especialidad;
		
		public buscardoctorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Cod", DbType="Int")]
		public System.Nullable<int> Hospital_Cod
		{
			get
			{
				return this._Hospital_Cod;
			}
			set
			{
				if ((this._Hospital_Cod != value))
				{
					this._Hospital_Cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doctor_No", DbType="Int")]
		public System.Nullable<int> Doctor_No
		{
			get
			{
				return this._Doctor_No;
			}
			set
			{
				if ((this._Doctor_No != value))
				{
					this._Doctor_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
	}
	
	public partial class buscarsalaResult
	{
		
		private System.Nullable<int> _Sala_Cod;
		
		private System.Nullable<int> _Cod_Hospital;
		
		private string _Nombre;
		
		private string _Especialidad;
		
		public buscarsalaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sala_Cod", DbType="Int")]
		public System.Nullable<int> Sala_Cod
		{
			get
			{
				return this._Sala_Cod;
			}
			set
			{
				if ((this._Sala_Cod != value))
				{
					this._Sala_Cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Hospital", DbType="Int")]
		public System.Nullable<int> Cod_Hospital
		{
			get
			{
				return this._Cod_Hospital;
			}
			set
			{
				if ((this._Cod_Hospital != value))
				{
					this._Cod_Hospital = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
	}
	
	public partial class listardoctoresResult
	{
		
		private System.Nullable<int> _Hospital_Cod;
		
		private System.Nullable<int> _Doctor_No;
		
		private string _Apellido;
		
		private string _Especialidad;
		
		public listardoctoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Cod", DbType="Int")]
		public System.Nullable<int> Hospital_Cod
		{
			get
			{
				return this._Hospital_Cod;
			}
			set
			{
				if ((this._Hospital_Cod != value))
				{
					this._Hospital_Cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doctor_No", DbType="Int")]
		public System.Nullable<int> Doctor_No
		{
			get
			{
				return this._Doctor_No;
			}
			set
			{
				if ((this._Doctor_No != value))
				{
					this._Doctor_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this._Apellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
	}
	
	public partial class listarsalasResult
	{
		
		private System.Nullable<int> _Sala_Cod;
		
		private System.Nullable<int> _Cod_Hospital;
		
		private string _Nombre;
		
		private string _Especialidad;
		
		public listarsalasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sala_Cod", DbType="Int")]
		public System.Nullable<int> Sala_Cod
		{
			get
			{
				return this._Sala_Cod;
			}
			set
			{
				if ((this._Sala_Cod != value))
				{
					this._Sala_Cod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_Hospital", DbType="Int")]
		public System.Nullable<int> Cod_Hospital
		{
			get
			{
				return this._Cod_Hospital;
			}
			set
			{
				if ((this._Cod_Hospital != value))
				{
					this._Cod_Hospital = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especialidad", DbType="VarChar(50)")]
		public string Especialidad
		{
			get
			{
				return this._Especialidad;
			}
			set
			{
				if ((this._Especialidad != value))
				{
					this._Especialidad = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
